service: sm-service-source

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  generatestatus:
    handler: handler.statusproducer
    events:
      - httpApi:
          path: /status
          method: get
